name: Download CloudflareSpeedTest

on:
  workflow_dispatch:  # 允许手动触发
  
jobs:
  download-and-extract:
    runs-on: ubuntu-latest
    permissions:
      contents: write      # 添加写入权限
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_TOKEN }}  # 使用 REPO_TOKEN 进行身份验证

      - name: Create working directory
        run: mkdir -p CloudflareSpeedTest
        
      - name: Download all files
        working-directory: CloudflareSpeedTest
        run: |
          # MacOS
          wget https://github.com/XIU2/CloudflareSpeedTest/releases/download/v2.2.5/CloudflareST_darwin_amd64.zip
          wget https://github.com/XIU2/CloudflareSpeedTest/releases/download/v2.2.5/CloudflareST_darwin_arm64.zip
          
          # Linux
          wget https://github.com/XIU2/CloudflareSpeedTest/releases/download/v2.2.5/CloudflareST_linux_386.tar.gz
          wget https://github.com/XIU2/CloudflareSpeedTest/releases/download/v2.2.5/CloudflareST_linux_amd64.tar.gz
          wget https://github.com/XIU2/CloudflareSpeedTest/releases/download/v2.2.5/CloudflareST_linux_arm64.tar.gz
          wget https://github.com/XIU2/CloudflareSpeedTest/releases/download/v2.2.5/CloudflareST_linux_armv5.tar.gz
          wget https://github.com/XIU2/CloudflareSpeedTest/releases/download/v2.2.5/CloudflareST_linux_armv6.tar.gz
          wget https://github.com/XIU2/CloudflareSpeedTest/releases/download/v2.2.5/CloudflareST_linux_armv7.tar.gz
          wget https://github.com/XIU2/CloudflareSpeedTest/releases/download/v2.2.5/CloudflareST_linux_mips.tar.gz
          wget https://github.com/XIU2/CloudflareSpeedTest/releases/download/v2.2.5/CloudflareST_linux_mips64.tar.gz
          wget https://github.com/XIU2/CloudflareSpeedTest/releases/download/v2.2.5/CloudflareST_linux_mipsle.tar.gz
          wget https://github.com/XIU2/CloudflareSpeedTest/releases/download/v2.2.5/CloudflareST_linux_mips64le.tar.gz
          
          # Windows
          wget https://github.com/XIU2/CloudflareSpeedTest/releases/download/v2.2.5/CloudflareST_windows_386.zip
          wget https://github.com/XIU2/CloudflareSpeedTest/releases/download/v2.2.5/CloudflareST_windows_amd64.zip
          wget https://github.com/XIU2/CloudflareSpeedTest/releases/download/v2.2.5/CloudflareST_windows_arm64.zip

      - name: Create extraction directories
        working-directory: CloudflareSpeedTest
        run: |
          mkdir -p extracted/windows extracted/linux extracted/macos

      - name: Extract ZIP files
        working-directory: CloudflareSpeedTest
        run: |
          for f in *.zip; do
            if [[ $f == *"windows"* ]]; then
              arch=$(echo $f | grep -o 'windows_[^.]*' | cut -d'_' -f2)
              unzip -o "$f" -d "extracted/windows/"
              mv "extracted/windows/CloudflareST.exe" "extracted/windows/CloudflareST_${arch}.exe"
            elif [[ $f == *"darwin"* ]]; then
              arch=$(echo $f | grep -o 'darwin_[^.]*' | cut -d'_' -f2)
              unzip -o "$f" -d "extracted/macos/"
              mv "extracted/macos/CloudflareST" "extracted/macos/CloudflareST_${arch}"
            fi
          done
          rm *.zip  # 删除所有 zip 文件

      - name: Extract TAR.GZ files
        working-directory: CloudflareSpeedTest
        run: |
          for f in *.tar.gz; do
            arch=$(echo $f | grep -o 'linux_[^.]*' | cut -d'_' -f2)
            tar -xzf "$f" -C "extracted/linux/"
            mv "extracted/linux/CloudflareST" "extracted/linux/CloudflareST_${arch}"
          done
          rm *.tar.gz  # 删除所有 tar.gz 文件

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Commit and push changes
        run: |
          git add CloudflareSpeedTest/
          git commit -m "Add CloudflareSpeedTest files"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}  # 设置环境变量

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cloudflare-speedtest-files
          path: CloudflareSpeedTest/extracted/
