name: Update IP List

on:
  schedule:
    - cron: '0 */12 * * *'  # 每12小时执行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  update-geoip:
    uses: ./.github/workflows/update-geoip.yml
    secrets: inherit
    
  update-ip-list:
    needs: update-geoip
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.REPO_TOKEN }}
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U requests geoip2
          
      - name: Download and process IP list
        run: |
          python3 -c '
          import json
          import requests
          import geoip2.database
          import os
          from collections import defaultdict

          # Cloudflare ASN
          CLOUDFLARE_ASNS = {13335, 209242}  # Cloudflare 的 ASN 号码

          # 创建目录
          os.makedirs("proxy_ips", exist_ok=True)

          # 下载IP列表
          response = requests.get("https://ip.rdone.me/list")
          data = response.json()

          # 创建国家分类字典
          country_ips = defaultdict(list)

          # 使用 GeoIP2 数据库
          reader = geoip2.database.Reader("data/GeoLite2-Country.mmdb")

          # 对IP进行分类
          for proxy in data["proxies"]:
              ip = proxy["ip"]
              try:
                  # 获取 IP 信息
                  response = reader.country(ip)
                  # 跳过 Cloudflare IP
                  if hasattr(response, "traits") and hasattr(response.traits, "autonomous_system_number"):
                      if response.traits.autonomous_system_number in CLOUDFLARE_ASNS:
                          continue
                  country = response.country.name or "Unknown"
                  country_ips[country].append(ip)
              except:
                  country_ips["Unknown"].append(ip)

          # 关闭数据库连接
          reader.close()

          # 写入总的IP列表
          with open("proxy_ips/ip_list.txt", "w") as f:
              for proxy in data["proxies"]:
                  ip = proxy["ip"]
                  try:
                      response = reader.country(ip)
                      if hasattr(response, "traits") and hasattr(response.traits, "autonomous_system_number"):
                          if response.traits.autonomous_system_number in CLOUDFLARE_ASNS:
                              continue
                      f.write(f"{ip}\n")
                  except:
                      f.write(f"{ip}\n")

          # 为每个国家创建单独的文件
          for country, ips in country_ips.items():
              filename = f"proxy_ips/ips_{country.lower().replace(" ", "_")}.txt"
              with open(filename, "w") as f:
                  for ip in ips:
                      f.write(f"{ip}\n")
          '
          
      - name: Commit and push if changed
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add proxy_ips/ip_list.txt
          git add proxy_ips/ips_*.txt
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Update IP list with country classification"
            git pull --rebase
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
