name: Merge IP Lists

on:
  schedule:
    - cron: '0 */6 * * *'  # 每6小时运行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  merge:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.REPO_TOKEN }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Create Directory and Merge IP Lists
        run: |
          # 创建目标目录
          mkdir -p ip_lists
          
          # 下载两个源文件
          curl -sSL "https://gitlab.com/rdone4425/ip/-/raw/main/merged_all.txt" -o temp1.txt
          curl -sSL "https://raw.githubusercontent.com/rdone44/juhe/refs/heads/main/ip_list.txt" -o temp2.txt
          
          # 合并文件并排序去重
          cat temp1.txt temp2.txt | sort -u > ip_lists/merged_ips.txt
          
          # 删除临时文件
          rm temp1.txt temp2.txt

      - name: Commit and Push
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          # 先暂存所有更改
          git add .
          
          # 拉取最新的更改
          git pull origin main --rebase
          
          if git diff --staged --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          
          git commit -m "Update merged IP lists [skip ci]"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }} 
