name: Update GeoIP Database

on:
  schedule:
    - cron: '0 0 * * 0'  # 每周日午夜执行
  workflow_dispatch:      # 允许手动触发

jobs:
  update-geoip:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.REPO_TOKEN }}
          
      - name: Download GeoIP database
        run: |
          mkdir -p data
          wget -O data/GeoLite2-Country.mmdb https://github.com/P3TERX/GeoLite.mmdb/raw/download/GeoLite2-Country.mmdb
          
      - name: Commit and push if changed
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add data/GeoLite2-Country.mmdb
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Update GeoIP database"
            git pull --rebase
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }} 
